<?php
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Imliments hook_user_login
 */
function blood_sugar_report_user_login(\Drupal\user\UserInterface $account) {
  $current_user = \Drupal::currentUser();
  $current_u_roles = $current_user->getRoles();
  if(in_array("blood_sugar_users", $current_u_roles)) {
		 // We want to redirect user on login.
	  $response = new RedirectResponse("/myspace");
	  $response->send();
	  return;
  }
}


/**
 * Implements hook_install.
 */
/*function blood_sugar_report_install() { 
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
      $user = \Drupal\user\Entity\User::create();

  //Mandatory settings
      $user->setPassword('test');
      $user->enforceIsNew();
      $user->setEmail('test@test.com');
      $user->setUsername('test'); //This username must be unique and accept only a-Z,0-9, - _ @ .

  //Optional settings
      $user->set("init", 'email');
      $user->set("langcode", $language);
      $user->set("preferred_langcode", $language);
      $user->set("preferred_admin_langcode", $language);
      //$user->set("setting_name", 'setting_value');
      $user->activate();

  //Save user
      $res = $user->save();
}*/
